export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <>
      {children}
    </>
  );
}
